server {
    listen 80;
    server_name app.virusinferno.xyz;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # This line is CRITICAL for React Router to work without 404 errors
        try_files $uri $uri/ /index.html;
    }
}